/**
 * Local YAML data loader for lookup tools.
 *
 * Reads the YAML files generated by `scripts/wethod-sync.sh` and provides
 * typed in-memory maps for persons, projects, and clients.
 *
 * Files are lazily loaded on first access and cached for the server lifetime.
 * No external YAML parser needed — the files use a simple, regular format.
 */

import { readFileSync } from "node:fs"
import { join } from "node:path"

// --- Types ---

export type PersonEntry = {
  id: number
  name: string
  surname: string
  is_external: boolean
}

export type ProjectEntry = {
  id: number
  name: string
  job_order: string | null
  client: string | null
  client_id: number | null
  pm_id: number | null
}

export type ClientEntry = {
  id: number
  name: string
}

// --- Parser ---

function readLines(filePath: string): string[] {
  try {
    return readFileSync(filePath, "utf-8").split("\n")
  } catch {
    return []
  }
}

/**
 * Parses wethod-persons.yaml
 *
 * Format:
 *   42: { name: "Salvatore", surname: "Lanzafame", is_external: false }
 */
function parsePersons(dataDir: string): Map<number, PersonEntry> {
  const map = new Map<number, PersonEntry>()
  const lines = readLines(join(dataDir, "wethod-persons.yaml"))

  const re =
    /^\s+(\d+):\s*\{\s*name:\s*"(.+?)",\s*surname:\s*"(.+?)",\s*is_external:\s*(true|false)\s*\}/

  for (const line of lines) {
    const m = line.match(re)
    if (m) {
      const id = Number(m[1])
      map.set(id, {
        id,
        name: m[2],
        surname: m[3],
        is_external: m[4] === "true"
      })
    }
  }

  return map
}

/**
 * Parses wethod-projects.yaml
 *
 * Format:
 *   25965:
 *     name: "Pomellato Closer Q1 2026"
 *     job_order: "511502"
 *     client: "Pomellato S.p.A."
 *     client_id: 1234
 *     pm_id: 270
 */
function parseProjects(dataDir: string): Map<number, ProjectEntry> {
  const map = new Map<number, ProjectEntry>()
  const lines = readLines(join(dataDir, "wethod-projects.yaml"))

  let currentId: number | null = null
  let current: Partial<ProjectEntry> = {}

  const idRe = /^\s{2}(\d+):$/
  const nameRe = /^\s{4}name:\s*"(.+)"$/
  const jobOrderRe = /^\s{4}job_order:\s*"?(.+?)"?$/
  const clientRe = /^\s{4}client:\s*"(.+)"$/
  const clientIdRe = /^\s{4}client_id:\s*(.+)$/
  const pmIdRe = /^\s{4}pm_id:\s*(.+)$/

  const flush = () => {
    if (currentId !== null && current.name) {
      map.set(currentId, {
        id: currentId,
        name: current.name,
        job_order: current.job_order ?? null,
        client: current.client ?? null,
        client_id: current.client_id ?? null,
        pm_id: current.pm_id ?? null
      })
    }
  }

  for (const line of lines) {
    const idMatch = line.match(idRe)
    if (idMatch) {
      flush()
      currentId = Number(idMatch[1])
      current = {}
      continue
    }

    const nameMatch = line.match(nameRe)
    if (nameMatch) {
      current.name = nameMatch[1]
      continue
    }

    const joMatch = line.match(jobOrderRe)
    if (joMatch) {
      const v = joMatch[1]
      current.job_order = v === "null" ? null : v
      continue
    }

    const clientMatch = line.match(clientRe)
    if (clientMatch) {
      const v = clientMatch[1]
      current.client = v === "unknown" ? null : v
      continue
    }

    const cidMatch = line.match(clientIdRe)
    if (cidMatch) {
      const v = cidMatch[1].trim()
      current.client_id = v === "null" ? null : Number(v)
      continue
    }

    const pmMatch = line.match(pmIdRe)
    if (pmMatch) {
      const v = pmMatch[1].trim()
      current.pm_id = v === "null" ? null : Number(v)
      continue
    }
  }
  flush()

  return map
}

/**
 * Parses wethod-clients.yaml
 *
 * Format:
 *   58: "Porsche Haus Srl"
 */
function parseClients(dataDir: string): Map<number, ClientEntry> {
  const map = new Map<number, ClientEntry>()
  const lines = readLines(join(dataDir, "wethod-clients.yaml"))

  const re = /^\s+(\d+):\s*"(.+)"$/

  for (const line of lines) {
    const m = line.match(re)
    if (m) {
      const id = Number(m[1])
      map.set(id, { id, name: m[2] })
    }
  }

  return map
}

// --- Cached loader ---

export class DataLoader {
  private dataDir: string

  constructor(dataDir: string) {
    this.dataDir = dataDir
  }

  getPersons(): Map<number, PersonEntry> {
    return parsePersons(this.dataDir)
  }

  getProjects(): Map<number, ProjectEntry> {
    return parseProjects(this.dataDir)
  }

  getClients(): Map<number, ClientEntry> {
    return parseClients(this.dataDir)
  }

  /** Resolves a person name from ID. Returns "Unknown (id)" if not found. */
  personName(id: number): string {
    const p = this.getPersons().get(id)
    return p ? `${p.name} ${p.surname}` : `Unknown (${id})`
  }

  /** Resolves a client name from ID. Returns "Unknown (id)" if not found. */
  clientName(id: number): string {
    const c = this.getClients().get(id)
    return c ? c.name : `Unknown (${id})`
  }
}
