/**
 * Local JSON data loader for lookup tools.
 *
 * Reads the JSON files generated by the `sync` MCP tool and stored in
 * `~/.mcp-wethod/{company}/`. Provides typed in-memory maps for persons,
 * projects, clients, and project types.
 *
 * Files are lazily loaded on first access.
 */

import { readFileSync } from "node:fs"
import { join } from "node:path"

// --- Types ---

export type PersonEntry = {
  id: number
  name: string
  surname: string
  is_external: boolean
}

export type ProjectEntry = {
  id: number
  name: string
  job_order: string | null
  client: string | null
  client_id: number | null
  pm_id: number | null
}

export type ClientEntry = {
  id: number
  name: string
}

export type ProjectTypeEntry = {
  id: number
  name: string
  chargeable: boolean
  hours_type: string
}

// --- Parser ---

function readJson<T>(filePath: string): T | null {
  try {
    return JSON.parse(readFileSync(filePath, "utf-8")) as T
  } catch {
    return null
  }
}

function toMap<T extends { id: number }>(items: T[] | null): Map<number, T> {
  const map = new Map<number, T>()
  if (items) {
    for (const item of items) {
      map.set(item.id, item)
    }
  }
  return map
}

// --- Cached loader ---

export class DataLoader {
  private dataDir: string

  constructor(dataDir: string) {
    this.dataDir = dataDir
  }

  getPersons(): Map<number, PersonEntry> {
    return toMap(readJson<PersonEntry[]>(join(this.dataDir, "persons.json")))
  }

  getProjects(): Map<number, ProjectEntry> {
    return toMap(readJson<ProjectEntry[]>(join(this.dataDir, "projects.json")))
  }

  getClients(): Map<number, ClientEntry> {
    return toMap(readJson<ClientEntry[]>(join(this.dataDir, "clients.json")))
  }

  getProjectTypes(): Map<number, ProjectTypeEntry> {
    return toMap(
      readJson<ProjectTypeEntry[]>(join(this.dataDir, "project-types.json")),
    )
  }

  /** Resolves a person name from ID. Returns "Unknown (id)" if not found. */
  personName(id: number): string {
    const p = this.getPersons().get(id)
    return p ? `${p.name} ${p.surname}` : `Unknown (${id})`
  }

  /** Resolves a client name from ID. Returns "Unknown (id)" if not found. */
  clientName(id: number): string {
    const c = this.getClients().get(id)
    return c ? c.name : `Unknown (${id})`
  }
}
