#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs"

const pkg = JSON.parse(readFileSync("package.json", "utf-8"))
const content = `// Auto-generated by scripts/generate-version.mjs — do not edit.\nexport const VERSION = "${pkg.version}"\n`
writeFileSync("src/version.mts", content, "utf-8")
